# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iUXTdQO8IK0xxLFnXZVB5VM86jFHAfdF
"""

pip install darts

from os.path import dirname, basename
from os import getcwd
import sys


def fix_pythonpath_if_working_locally():
    """Add the parent path to pythonpath if current working dir is darts/examples"""
    cwd = getcwd()
    if basename(cwd) == 'examples':
        sys.path.insert(0, dirname(cwd))

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from darts import TimeSeries
from darts.models import NBEATSModel
from darts.dataprocessing.transformers import Scaler, MissingValuesFiller
from darts.metrics import mape, r2_score

from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/dataset4.csv"
df = pd.read_csv(path)

df.head()

df.dropna(inplace=True)

df['Date_Time'] = pd.to_datetime(df['Date_Time'])

df.head()

ser = TimeSeries.from_dataframe(df=df,time_col="Date_Time")

scaler_en = Scaler()
series_en_transformed = scaler_en.fit_transform(ser['Voltage(V)'])
train, val = series_en_transformed.split_after(pd.Timestamp('1/30/2018  10:26:10 AM'))
#series_en_transformed.plot()
scaler_en.inverse_transform(series_en_transformed).plot()

#train, val = ser.split_after(pd.Timestamp('1/30/2018  10:26:10 AM'))

model_nbeats = NBEATSModel(
    input_chunk_length=300,
    output_chunk_length=28,
    generic_architecture=True,
    num_stacks=10,
    num_blocks=1,
    num_layers=4,
    layer_widths=512,
    n_epochs=500,
    nr_epochs_val_period=1,
    batch_size=16,
    model_name='nbeats_run',
    force_reset=True
)

model_nbeats.fit(train, val_series=val, verbose=True)

from darts.metrics import mae

def eval_model(model):
    pred_series = model.predict(n=1000)
    plt.figure(figsize=(8,5))
    series_en_transformed.plot(label='actual')
    pred_series.plot(label='forecast')
    plt.title('MAE: {}'.format(mae(pred_series, val)))
    plt.legend()
    
    
    
    
eval_model(model_nbeats)

def display_forecast(pred_series, ts_transformed, forecast_type, start_date=None):
    plt.figure(figsize=(8,5))
    ax = plt.axes()
    plt.xlabel('Time (minutes)')
    plt.ylabel('Charge Capacity (Ah)')
    plt.yticks(np.arange(-3,4))
    ax.spines['top'].set_visible(True)
    ax.spines['right'].set_visible(True)
    ax.spines['bottom'].set_visible(True)
    ax.spines['left'].set_visible(True)
    #if (start_date):
        #ts_transformed = ts_transformed.drop_after(start_date)
    ts_transformed.univariate_component(0)[750:1250].plot(label='Ground Truth')
    pred_series.plot(label=('historic ' + forecast_type + ' forecasts'))
    plt.title('R2: {}'.format(r2_score(ts_transformed.univariate_component(0), pred_series)))
    plt.legend();

pred_series = model_nbeats.historical_forecasts(
    train,
    start=pd.Timestamp('1/29/2018  1:04:10 AM'), 
    forecast_horizon=850,
    stride=5,
    retrain=False,
    verbose=True
)

mae(series_en_transformed, pred_series)

horizon = [10,30,50,80,100,200,300,400,500,600,700,800,850]
mae_values = []
ccmae = [0.008853838689946967,0.009215470209077523,0.006998402349994076,0.00781268686576152,0.008740313487471537,0.018718922583174685,0.018124344737273732,0.019361692328529502,0.028095693776796694,0.02146549651121725,0.022255746751272534,0.03012719980138769,0.037091732762376727]

plt.figure(figsize=(7,5),edgecolor="black")
ax = plt.axes()
ser[750:1250].plot(label='Ground Truth')
scaler_en.inverse_transform(pred_series)[0:50].plot(label=('Prediction (horizon 30)'))
plt.xlabel('Time (minutes)')
plt.ylabel('Charge Capacity (Ah)')
plt.yticks(np.arange(-1,4))
ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)
ax.spines['bottom'].set_visible(True)
ax.spines['left'].set_visible(True)
#plt.savefig("/content/drive/MyDrive/ChargeCapacity_dataset4_horizon30_nbeats.pdf",bbox_inches="tight")
#ser[750:1250].plot(label='Ground Truth')
#scaler_en.inverse_transform(pred_series)[0:50].plot(label=('Prediction (horizon 5)'))

pwd